Section "InputClass"
    Identifier "Inateck KB01105 Touchpad"
    Driver "libinput"
    Option "NaturalScrolling" "true"
    Option "AccelSpeed" "0.4"
    Option "Tapping" "On"
    Option "TappingDrag" "On"
EndSection
