PREFIX="${XDG_DATA_HOME}/regexghost"

normal:
	mkdir -p "${PREFIX}/terminal"
	cp ls_aliases.bash "${PREFIX}/terminal/ls_aliases.bash"
	cp autocompletion.bash "${PREFIX}/terminal/autocompletion.bash"
	sudo cp 50-inateck-touchpad.conf /etc/X11/xorg.conf.d/50-inateck-touchpad.conf
