PREFIX="${XDG_DATA_HOME}/regexghost/wm-scripts"

normal:
	mkdir -p ${PREFIX}
	cp altgrtosuper.sh ${PREFIX}/altgrtosuper.sh
	cp volume.sh ${PREFIX}/volume.sh
	cp dmenu-runner.sh ${PREFIX}/dmenu-runner.sh
	cp bookmarks.sh ${PREFIX}/bookmarks.sh
