PREFIX="${XDG_DATA_HOME}/regexghost/wm-scripts"

normal:
	mkdir -p ${PREFIX}
	cp altgrtosuper.sh ${PREFIX}/altgrtosuper.sh
	cp volume.sh ${PREFIX}/volume.sh
	cp dmenu-runner.sh ${PREFIX}/dmenu-runner.sh
	cp dmenu-programs.sh ${PREFIX}/dmenu-programs.sh
	cp bookmarks.sh ${PREFIX}/bookmarks.sh
	cp keyboard-settings.sh ${PREFIX}/keyboard-settings.sh
	cp jwm-xinit.sh ${PREFIX}/jwm-xinit.sh
	cp jwm-scratchpad.sh ${PREFIX}/jwm-scratchpad.sh
	cp snippets.sh ${PREFIX}/snippets.sh
	cp launch-stream.sh ${PREFIX}/launch-stream.sh
	cp dmenu-wiki.sh ${PREFIX}/dmenu-wiki.sh
