# vim:ft=kitty

## name: Adwaita dark
## license: MIT
## author: Emil Löfquist (https://github.com/ewal)
## upstream: https://github.com/ewal/kitty-adwaita/blob/main/adwaita_dark.conf
## blurb: Adwaita dark - based on https://github.com/Mofiqul/adwaita.nvim

background                #231f20
foreground                #ffffff
# background                #dcdcdc
# foreground                #323232

selection_background      #2b2b2b
selection_foreground      #ffffff

url_color                 #1a5fb4

wayland_titlebar_color    system
macos_titlebar_color      system

cursor                    #deddda
cursor_text_color         #1d1d1d

active_border_color       #4f4f4f
inactive_border_color     #282828
bell_border_color         #ed333b
visual_bell_color         none

active_tab_background     #242424 
active_tab_foreground     #fcfcfc
inactive_tab_background   #303030
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color0                    #17acf1
color1                    #fd3762
color2                    #1ba172
color3                    #f7c067
color4                    #f77067
color5                    #a35fc8
color6                    #4074b4
color7                    #d8d8d8

color8                    #159ddc
color9                    #f22c57
color10                   #189066
color11                   #ddab5c
color12                   #df635d
color13                   #995abe
color14                   #306bb4
color15                   #eeeeee
