wheel_up ignore
wheel_down ignore
wheel_left ignore
wheel_right ignore

q ignore
ctrl+q quit
shift+q ignore
p ignore

right seek 5
left seek -5
up seek 30
down seek -30

shift+right add chapter 1
shift+left add chapter -1
enter write-watch-later-config;playlist-next
shift+enter write-watch-later-config;playlist-prev

d add speed 0.1
s add speed -0.1
r set speed 1
g cycle-values speed 2 1

c show-text ${chapter-list} 3000
u show-text ${playlist} 3000
